services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
      - 8000:8000
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db
    networks:
      - foodlicense

  db:
    image: postgres:trixie
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Pintu332@
      POSTGRES_DB: foodlicense
    networks:
      - foodlicense

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - foodlicense

volumes:
  postgres-data:

networks:
  foodlicense:
    driver: bridge
